sudo: required
services:
  - docker

before_install:
  - docker build -t docker-training-react -f frontend/Dockerfile.dev frontend/

script:
  - docker run docker-training-react npm run test -- --coverage