version: "3.9"

services:
  redis:
    image: redis:latest
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5445:5432"
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=oyapparov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=rudna
    ports:
      - "9000:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PG_DATABASE=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
    depends_on:
      - postgres
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - api
      - client
