version: "3.9"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PG_DATABASE=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app