sudo: required
services:
  - docker

before_install:
  - docker build -t oyapparov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run oyapparov/react-test npm test -- --coverage

after_success:
  - docker build -t oyapparov/multi-client ./client
  - docker build -t oyapparov/multi-nginx ./nginx
  - docker build -t oyapparov/multi-server ./server
  - docker build -t oyapparov/multi-worker ./worker
  # Log into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stin
  # Push all images to Docker Hub
  - docker push oyapparov/multi-client
  - docker push oyapparov/multi-nginx
  - docker push oyapparov/multi-server
  - docker push oyapparov/multi-worker